import { Injectable, Inject } from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';
import { PrismaService } from '@app/prisma';
import { TICKET_REPOSITORY, ITicketRepository } from '@app/tickets';
import { CreateTicketDto } from './create-ticket.dto';

@Injectable()
export class CreateTicketHandler {
    constructor(
        @Inject(TICKET_REPOSITORY)
        private readonly ticketRepository: ITicketRepository,
        private readonly prisma: PrismaService,
    ) { }

    async execute(dto: CreateTicketDto, reporterId: string): Promise<any> {
        // 1. Create the ticket
        const ticket = await this.ticketRepository.save({
            id: undefined, // will be auto-generated by Prisma
            issueName: dto.issueName,
            issueType: dto.issueType,
            description: dto.description,
            priority: dto.priority ?? 'Medium',
            status: 'OPEN',
            reporterId,
            sessionId: dto.sessionId,
            attachment: dto.attachment,
        });

        // 2. Fetch all Exam Officers to notify
        const examOfficers = await this.prisma.user.findMany({
            where: { role: 'EXAM_OFFICER' },
            select: { id: true },
        });

        // 3. Create in-app notifications for each Exam Officer
        if (examOfficers.length > 0) {
            const reporter = await this.prisma.user.findUnique({
                where: { id: reporterId },
                select: { fullName: true, role: true },
            });

            await this.prisma.notification.createMany({
                data: examOfficers.map(eo => ({
                    id: uuidv4(),
                    toUserId: eo.id,
                    fromId: reporterId,
                    title: `🎫 New Ticket: ${dto.issueName}`,
                    message: `${reporter?.fullName ?? 'A staff member'} (${reporter?.role}) reported a new ticket: "${dto.issueName}". Priority: ${dto.priority ?? 'Medium'}.`,
                    channel: 'IN_APP',
                    meta: { ticketId: ticket.id, issueType: dto.issueType },
                })),
            });
        }

        return ticket;
    }
}
